### PR TITLE
Uninstall now restores backup of crosh

### PR DESCRIPTION
**Pull request by oliverwarne**
This might fix issue #5 

Works by making a backup of the crosh during installation, then restoring that during uninstall. This way you guys don't have to maintain/hold onto a copy of crosh.

I haven't tested this at all, mainly because I don't want to install cri then uninstall it because it would remove my chroots.

### CODE REVIEW

**Comment by smerkousdavid** [comment]
Can't merge contains conflicts, will do though

**Comment by smerkousdavid** [comment]
Need option to pull though, because cri will stick on powerwash, that's the reason why we did that in the first place

**Comment by OliverWarne** [comment]
I'll manually merge it

**Comment by oliverwarne** [comment]
Nevermind

**Pull request closed without merging**
